using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using MiniChess.GameplayTags;
using UnityEditor;
using UnityEngine;

namespace MiniChess.EditorTools
{
    public static class TagCodeGenerator
    {
        private const string k_RegistryPath = "Assets/Data/Tags/GameplayTagRegistry.asset";
        private const string k_OutputPath = "Assets/Scripts/GameplayTags/Generated/GameplayTagConstants.g.cs";

        // C# reserved keywords that need @ prefix when used as identifiers.
        private static readonly HashSet<string> s_keywords = new HashSet<string>(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
            "checked", "class", "const", "continue", "decimal", "default", "delegate", "do",
            "double", "else", "enum", "event", "explicit", "extern", "false", "finally",
            "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int",
            "interface", "internal", "is", "lock", "long", "namespace", "new", "null",
            "object", "operator", "out", "override", "params", "private", "protected",
            "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof",
            "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
            "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
            "virtual", "void", "volatile", "while"
        };

        [MenuItem("MiniChess/Regenerate GameplayTag Constants")]
        public static void Regenerate()
        {
            Generate();
        }

        public static void Generate()
        {
            var tagStrings = LoadRegisteredTags();
            if (tagStrings == null)
            {
                Debug.LogWarning("[TagCodeGenerator] Could not load TagRegistry.");
                return;
            }

            var hierarchy = BuildHierarchy(tagStrings);
            string code = EmitCode(hierarchy);
            WriteFile(code);

            AssetDatabase.Refresh();
            Debug.Log($"[TagCodeGenerator] Generated {tagStrings.Count} tag constants to {k_OutputPath}");
        }

        private static List<string> LoadRegisteredTags()
        {
            var registry = AssetDatabase.LoadAssetAtPath<TagRegistry>(k_RegistryPath);
            if (registry == null)
                return null;

            return registry.Entries
                .Select(e =>
                {
                    try { return e.Tag.Value; }
                    catch { return null; }
                })
                .Where(v => !string.IsNullOrEmpty(v))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(v => v, StringComparer.OrdinalIgnoreCase)
                .ToList();
        }

        private class HierarchyNode
        {
            public string Segment;
            public Dictionary<string, HierarchyNode> Children = new Dictionary<string, HierarchyNode>(StringComparer.Ordinal);
            public string FullTag; // non-null for leaf nodes
        }

        private static HierarchyNode BuildHierarchy(List<string> tags)
        {
            var root = new HierarchyNode { Segment = "GameplayTagConstants" };

            foreach (var tag in tags)
            {
                var parts = tag.Split('.');
                var current = root;

                for (int i = 0; i < parts.Length; i++)
                {
                    var part = parts[i];
                    if (!current.Children.TryGetValue(part, out var child))
                    {
                        child = new HierarchyNode { Segment = part };
                        current.Children[part] = child;
                    }
                    current = child;
                }

                current.FullTag = tag;
            }

            return root;
        }

        private static string EmitCode(HierarchyNode root)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Generated by MiniChess.EditorTools.TagCodeGenerator");
            sb.AppendLine("// Changes to this file will be overwritten when the TagRegistry is updated.");
            sb.AppendLine();
            sb.AppendLine("using MiniChess.GameplayTags;");
            sb.AppendLine();
            sb.AppendLine("namespace MiniChess.GameplayTags.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class GameplayTagConstants");
            sb.AppendLine("    {");

            bool firstRoot = true;
            foreach (var child in root.Children.Values.OrderBy(c => c.Segment, StringComparer.Ordinal))
            {
                EmitClass(sb, child, "        ", ref firstRoot);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitClass(StringBuilder sb, HierarchyNode node, string indent, ref bool firstMember)
        {
            string className = SanitizeIdentifier(node.Segment);
            sb.AppendLine($"{indent}public static class {className}");
            sb.AppendLine($"{indent}{{");

            string innerIndent = indent + "    ";

            // Emit leaf fields
            var leafChildren = node.Children.Values.Where(c => c.Children.Count == 0).OrderBy(c => c.Segment, StringComparer.Ordinal);
            var nestedChildren = node.Children.Values.Where(c => c.Children.Count > 0).OrderBy(c => c.Segment, StringComparer.Ordinal);

            foreach (var leaf in leafChildren)
            {
                int hash = GameplayTag.ComputeTagHash(leaf.FullTag);
                string fieldName = SanitizeIdentifier(leaf.Segment);
                sb.AppendLine($"{innerIndent}public static readonly GameplayTag {fieldName} = new GameplayTag({hash}, \"{leaf.FullTag}\");");
            }

            // Emit this node's own tag if it's also a leaf
            if (node.FullTag != null)
            {
                int hash = GameplayTag.ComputeTagHash(node.FullTag);
                sb.AppendLine($"{innerIndent}public static readonly GameplayTag Tag = new GameplayTag({hash}, \"{node.FullTag}\");");
            }

            // Emit nested classes
            bool nestedFirst = true;
            foreach (var nested in nestedChildren)
            {
                EmitClass(sb, nested, innerIndent, ref nestedFirst);
            }

            sb.AppendLine($"{indent}}}");
        }

        private static string SanitizeIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name))
                return "_Empty";

            // Replace invalid characters with underscore
            var sb = new StringBuilder();
            foreach (char c in name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }

            string result = sb.ToString();

            // Ensure starts with letter or underscore
            if (result.Length > 0 && char.IsDigit(result[0]))
                result = "_" + result;

            // Handle reserved keywords
            if (s_keywords.Contains(result))
                result = "@" + result;

            return result;
        }

        private static void WriteFile(string content)
        {
            string dir = Path.GetDirectoryName(k_OutputPath);
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            // Only write if content changed to avoid unnecessary recompilation
            if (File.Exists(k_OutputPath))
            {
                string existing = File.ReadAllText(k_OutputPath);
                if (existing == content)
                    return;
            }

            File.WriteAllText(k_OutputPath, content, Encoding.UTF8);
        }
    }
}
